production:
  user: fedoraAdmin
  password: _FedAdminPa55_
  url: http://avalon.library.ucsc.edu:8983/fedora
development:
  user: fedoraAdmin
  password: _FedAdminPa55_
  url: http://avalon.library.ucsc.edu:8983/fedora
test: &TEST  
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8983/fedora-test
