---
development:
   host: merritt.cdlib.org
   username: ethenry
   password: A4rgTeth
   profiles: 
     - merritt_demo_content
     - ucsc_lib_sc_content
     - ucsc_lib_etd_content
     - ucsc_lib_grateful_dead_content
     - ucsc_lib_promweek_content
     - ucsc_lib_regional_history_content
