# This is a sample config file that does not have multiple solr instances. You will also need to be sure to
# edit the fedora.yml file to match the solr URL for active-fedora. 
production:
  url: http://avalon.library.ucsc.edu:8983/solr/
development:
  url: http://avalon.library.ucsc.edu:8983/solr/
test: &TEST
  url: http://127.0.0.1:8983/solr/test

